### PR TITLE
Update fork with commits from upstream

### PR DESCRIPTION
**Pull request by DunderRoffe**
Highlights

Fix possible socket error when FOTA
Fix handling of separate responses from LWM2M server

Various documentation commits and sample code changes which we are not interested in but they do not affect our code so it is better to keep the commit tree from upstream intact

### CODE REVIEW

**Comment by DunderRoffe** [comment]
I encourage everyone to test this out on their boards.

I have been running it for a couple of hours sending lock / unlock commands. Seems fine so far

**Comment by linusnielsen** [comment]
Looks ok to me. I have tested it on wolfenstein, and it seems to work fine.

**Comment by DunderRoffe** [comment]
Please also comment if you think we are bumping too much

**Comment by linusnielsen** [comment]
> Please also comment if you think we are bumping too much

I think it's perfectly ok. We want to stay in sync with the official zephyr.

**Comment by endian-benjamin** [comment]
Looks harmless enough to me :+1:

**Pull request merged**
